@local = http://localhost:3000
@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI5ZjA2YjhhMGIyZWFmNDFiNWY2ZDEiLCJpYXQiOjE3NDc2ODE4MTR9.HtutLwt6QGoEDQAj6_INWhuHwc88S7vmE_Ska9VgkeE
@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODI5ZjhiZTY1YzQ2ZDI5NWJhZTY4OWQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDc2MDcyNDd9.2MbM43hO4bLmqzPzO4Vt1-0me30LtDmK7Qd1yneC6bs
@trainerToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJhNTYxMDg4YTM5NzI5ZTk2ZDVmNTgiLCJyb2xlIjoidHJhaW5lciIsImlhdCI6MTc0NzYwODk2OX0.JN0JIx6rh5RByaFZs_nnRNaRxbevgdVA60k6V_cpyLs

@trainerToken2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJjZTFjZTg4NjM2MzZkZmI1NWI5ZWIiLCJpYXQiOjE3NDc3NzE4NTh9.P7iSO_lhermugB5im2Twiy26GWWyfOjEulEVcK7V-yI

@userToken2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODJlM2E3NjdlOThhNGRiY2M1YTMzNzYiLCJpYXQiOjE3NDc4NjAxNTd9.GT10T1nuHIgt41pWfP7OOtjf3ERvz_JucwAB-w5GRN8

Content-Type: application/json

{
  "firstName": "Ad",
  "lastName": "dd",
  "email": "123dddr@asdd.com",
  "password": "cAds!1244",
  "stats": {
    "weight": 40,
    "height": 220
  },
  "age": 18,
  "gender":"male"
}

###
POST {{local}}/athletix/auth/login
Content-Type: application/json

{
     "email":"t3@trainer.com",
     "password": "Dd!dd1234"

}

###
GET {{local}}/athletix/users/me
x-auth-token:{{userToken}}

###
PUT {{local}}/athletix/users/me
x-auth-token:{{userToken}}
Content-Type: application/json

{
    "firstName":"ddd",
    "lastName":"ddd",
    "email":"ddd@ddd.com"

}

###
GET {{local}}/athletix/users/admin
x-auth-token:{{adminToken}}

###
PUT {{local}}/athletix/users/trainers/682a561088a39729e96d5f58/assign-trainer
x-auth-token:{{trainerToken}}
Content-Type: application/json

{
  "trainerId":"682a561088a39729e96d5f58"
}



### get trainer clients
 GET {{local}}/athletix/users/trainers/my-clients
x-auth-token: {{trainerToken}}



###
 GET {{local}}/athletix/users/admin
x-auth-token: {{adminToken}}

### 
POST {{local}}/athletix/users/admin
x-auth-token: {{adminToken}}
Content-Type: application/json

{
    "image": {
      "url": "https://static.vecteezy.com/system/resources/previews/000/595/510/non_2x/vector-object-and-icons-for-sport-label-gym-badge-fitness-logo-design.jpg",
      "alt": "Profile"
    },
    "firstName": "Ad",
    "lastName": "dd",
    "email": "trainer25@asdd.com",
    "age": 18,
    "gender": "male",
    "password":"Add@trainer1234"
  }

  
### delete a trainer by admin
DELETE  {{local}}/athletix/users/admin/trainer/682ce1ce8863636dfb55b9eb
x-auth-token:{{adminToken}}
Content-Type: application/json

{
  "status":"reject"
}

### get delete requests
GET {{local}}/athletix/users/admin/delete-request
x-auth-token: {{adminToken}}

###
GET {{local}}/athletix/auth/role
x-auth-token:{{adminToken}}

###
POST {{local}}/athletix/program
x-auth-token:{{trainerToken2}}

{
  "name": "תכנית חיטוב למתחילים",
  "description": "תכנית של 6 שבועות לחיטוב וחיזוק כללי",
  "trainer": "60f1c2a4d5d5c2a4d5d5c2a4",
  "durationWeeks": 6,
  "difficulty": "beginner",
  "days": [
    {
      "day": "Sunday",
      "exercises": [
        {
          "name": "Squats",
          "sets": 3,
          "reps": 12,
          "restSeconds": 60,
          "notes": "שמור על גב ישר"
        },
        {
          "name": "Push-ups",
          "sets": 3,
          "reps": 10
        }
      ]
    },
    {
      "day": "Tuesday",
      "exercises": [
        {
          "name": "Deadlifts",
          "sets": 4,
          "reps": 8,
          "restSeconds": 90
        }
      ]
    }
  ],
  "attachments": [
    {
      "filename": "program-guide.pdf",
      "url": "https://example.com/files/program-guide.pdf",
      "mimetype": "application/pdf",
      "size": 102400
    }
  ]
}


